-- ================================================================
-- Seed Nifty 50 Stocks (as of March 2026)
-- Symbols use NSE ticker format suffixed with .NS for yfinance
-- ================================================================

INSERT INTO stocks (symbol, name, sector, is_nifty50) VALUES
    ('RELIANCE.NS',     'Reliance Industries',          'Energy',               TRUE),
    ('TCS.NS',          'Tata Consultancy Services',    'Information Technology', TRUE),
    ('HDFCBANK.NS',     'HDFC Bank',                    'Financial Services',    TRUE),
    ('INFY.NS',         'Infosys',                      'Information Technology', TRUE),
    ('ICICIBANK.NS',    'ICICI Bank',                    'Financial Services',    TRUE),
    ('HINDUNILVR.NS',   'Hindustan Unilever',           'FMCG',                 TRUE),
    ('SBIN.NS',         'State Bank of India',          'Financial Services',    TRUE),
    ('BHARTIARTL.NS',   'Bharti Airtel',                'Telecommunication',     TRUE),
    ('ITC.NS',          'ITC Limited',                  'FMCG',                 TRUE),
    ('KOTAKBANK.NS',    'Kotak Mahindra Bank',          'Financial Services',    TRUE),
    ('LT.NS',           'Larsen & Toubro',              'Construction',          TRUE),
    ('HCLTECH.NS',      'HCL Technologies',             'Information Technology', TRUE),
    ('AXISBANK.NS',     'Axis Bank',                    'Financial Services',    TRUE),
    ('ASIANPAINT.NS',   'Asian Paints',                 'Consumer Durables',     TRUE),
    ('MARUTI.NS',       'Maruti Suzuki',                'Automobile',            TRUE),
    ('SUNPHARMA.NS',    'Sun Pharmaceutical',           'Healthcare',            TRUE),
    ('TITAN.NS',        'Titan Company',                'Consumer Durables',     TRUE),
    ('BAJFINANCE.NS',   'Bajaj Finance',                'Financial Services',    TRUE),
    ('DMART.NS',        'Avenue Supermarts',            'Consumer Services',     TRUE),
    ('WIPRO.NS',        'Wipro',                        'Information Technology', TRUE),
    ('ULTRACEMCO.NS',   'UltraTech Cement',             'Construction Materials', TRUE),
    ('ONGC.NS',         'Oil & Natural Gas Corp',       'Energy',               TRUE),
    ('NTPC.NS',         'NTPC Limited',                 'Power',                TRUE),
    ('TATAMOTORS.NS',   'Tata Motors',                  'Automobile',            TRUE),
    ('JSWSTEEL.NS',     'JSW Steel',                    'Metals & Mining',       TRUE),
    ('POWERGRID.NS',    'Power Grid Corp',              'Power',                TRUE),
    ('M&M.NS',          'Mahindra & Mahindra',          'Automobile',            TRUE),
    ('TATASTEEL.NS',    'Tata Steel',                   'Metals & Mining',       TRUE),
    ('ADANIENT.NS',     'Adani Enterprises',            'Diversified',           TRUE),
    ('ADANIPORTS.NS',   'Adani Ports & SEZ',            'Infrastructure',        TRUE),
    ('BAJAJFINSV.NS',   'Bajaj Finserv',                'Financial Services',    TRUE),
    ('COALINDIA.NS',    'Coal India',                   'Metals & Mining',       TRUE),
    ('TECHM.NS',        'Tech Mahindra',                'Information Technology', TRUE),
    ('HDFCLIFE.NS',     'HDFC Life Insurance',          'Financial Services',    TRUE),
    ('SBILIFE.NS',      'SBI Life Insurance',           'Financial Services',    TRUE),
    ('GRASIM.NS',       'Grasim Industries',            'Construction Materials', TRUE),
    ('DIVISLAB.NS',     'Divi''s Laboratories',         'Healthcare',            TRUE),
    ('INDUSINDBK.NS',   'IndusInd Bank',                'Financial Services',    TRUE),
    ('BPCL.NS',         'Bharat Petroleum',             'Energy',               TRUE),
    ('BRITANNIA.NS',    'Britannia Industries',         'FMCG',                 TRUE),
    ('CIPLA.NS',        'Cipla',                        'Healthcare',            TRUE),
    ('EICHERMOT.NS',    'Eicher Motors',                'Automobile',            TRUE),
    ('NESTLEIND.NS',    'Nestle India',                 'FMCG',                 TRUE),
    ('DRREDDY.NS',      'Dr Reddy''s Laboratories',     'Healthcare',            TRUE),
    ('APOLLOHOSP.NS',   'Apollo Hospitals',             'Healthcare',            TRUE),
    ('TATACONSUM.NS',   'Tata Consumer Products',       'FMCG',                 TRUE),
    ('HEROMOTOCO.NS',   'Hero MotoCorp',                'Automobile',            TRUE),
    ('HINDALCO.NS',     'Hindalco Industries',          'Metals & Mining',       TRUE),
    ('BAJAJ-AUTO.NS',   'Bajaj Auto',                   'Automobile',            TRUE),
    ('WIPRO.NS',        'Wipro',                        'Information Technology', TRUE)
ON CONFLICT (symbol) DO NOTHING;
